allauth/account/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r"^signup/$", views.signup, name="account_signup"),
    url(r"^login/$", views.login, name="account_login"),
    url(r"^logout/$", views.logout, name="account_logout"),

    url(r"^password/change/$", views.password_change,
        name="account_change_password"),
    url(r"^password/set/$", views.password_set, name="account_set_password"),

    url(r"^inactive/$", views.account_inactive, name="account_inactive"),

    # E-mail
    url(r"^email/$", views.email, name="account_email"),
    url(r"^confirm-email/$", views.email_verification_sent,
        name="account_email_verification_sent"),
    url(r"^confirm-email/(?P<key>[-:\w]+)/$", views.confirm_email,
        name="account_confirm_email"),

    # password reset
    url(r"^password/reset/$", views.password_reset,
        name="account_reset_password"),
    url(r"^password/reset/done/$", views.password_reset_done,
        name="account_reset_password_done"),
    url(r"^password/reset/key/(?P<uidb36>[0-9A-Za-z]+)-(?P<key>.+)/$",
        views.password_reset_from_key,
        name="account_reset_password_from_key"),
    url(r"^password/reset/key/done/$", views.password_reset_from_key_done,
        name="account_reset_password_from_key_done"),
]

allauth/socialaccount/providers/agave/urls.py
from allauth.socialaccount.providers.agave.provider import AgaveProvider
from allauth.socialaccount.providers.oauth2.urls import default_urlpatterns


urlpatterns = default_urlpatterns(AgaveProvider)

allauth/socialaccount/providers/asana/urls.py
from allauth.socialaccount.providers.oauth2.urls import default_urlpatterns

from .provider import AsanaProvider


urlpatterns = default_urlpatterns(AsanaProvider)

allauth/socialaccount/providers/auth0/urls.py
# -*- coding: utf-8 -*-
from allauth.socialaccount.providers.auth0.provider import Auth0Provider
from allauth.socialaccount.providers.oauth2.urls import default_urlpatterns


urlpatterns = default_urlpatterns(Auth0Provider)

allauth/socialaccount/providers/azure/urls.py
from allauth.socialaccount.providers.oauth2.urls import default_urlpatterns

from .provider import AzureProvider


urlpatterns = default_urlpatterns(AzureProvider)

allauth/socialaccount/providers/baidu/urls.py
from allauth.socialaccount.providers.oauth2.urls import default_urlpatterns

from .provider import BaiduProvider


urlpatterns = default_urlpatterns(BaiduProvider)

allauth/socialaccount/providers/bitly/urls.py
from allauth.socialaccount.providers.oauth2.urls import default_urlpatterns

from .provider import BitlyProvider


urlpatterns = default_urlpatterns(BitlyProvider)

allauth/socialaccount/providers/box/urls.py
from allauth.socialaccount.providers.oauth.urls import default_urlpatterns

from .provider import BoxOAuth2Provider


urlpatterns = default_urlpatterns(BoxOAuth2Provider)

allauth/socialaccount/providers/cern/urls.py
from allauth.socialaccount.providers.oauth2.urls import default_urlpatterns

from .provider import CernProvider


urlpatterns = default_urlpatterns(CernProvider)

allauth/socialaccount/providers/daum/urls.py
from allauth.socialaccount.providers.oauth2.urls import default_urlpatterns

from .provider import DaumProvider


urlpatterns = default_urlpatterns(DaumProvider)

allauth/socialaccount/providers/fxa/urls.py
from allauth.socialaccount.providers.oauth2.urls import default_urlpatterns

from .provider import FirefoxAccountsProvider


urlpatterns = default_urlpatterns(FirefoxAccountsProvider)

allauth/socialaccount/providers/hubic/urls.py
from allauth.socialaccount.providers.oauth2.urls import default_urlpatterns

from .provider import HubicProvider


urlpatterns = default_urlpatterns(HubicProvider)

allauth/socialaccount/providers/kakao/urls.py
from allauth.socialaccount.providers.oauth2.urls import default_urlpatterns

from .provider import KakaoProvider


urlpatterns = default_urlpatterns(KakaoProvider)

allauth/socialaccount/providers/line/urls.py
from allauth.socialaccount.providers.oauth2.urls import default_urlpatterns

from .provider import LineProvider


urlpatterns = default_urlpatterns(LineProvider)

allauth/socialaccount/providers/naver/urls.py
from allauth.socialaccount.providers.oauth2.urls import default_urlpatterns

from .provider import NaverProvider


urlpatterns = default_urlpatterns(NaverProvider)

allauth/socialaccount/providers/vk/urls.py
from allauth.socialaccount.providers.oauth2.urls import default_urlpatterns

from .provider import VKProvider


urlpatterns = default_urlpatterns(VKProvider)

allauth/socialaccount/providers/xing/urls.py
from allauth.socialaccount.providers.oauth.urls import default_urlpatterns

from .provider import XingProvider


urlpatterns = default_urlpatterns(XingProvider)

allauth/socialaccount/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^login/cancelled/$', views.login_cancelled,
        name='socialaccount_login_cancelled'),
    url(r'^login/error/$', views.login_error,
        name='socialaccount_login_error'),
    url(r'^signup/$', views.signup, name='socialaccount_signup'),
    url(r'^connections/$', views.connections, name='socialaccount_connections')
]

allauth/urls.py
from importlib import import_module

from django.conf.urls import include, url

from allauth.socialaccount import providers

from . import app_settings


urlpatterns = [url(r'^', include('allauth.account.urls'))]

if app_settings.SOCIALACCOUNT_ENABLED:
    urlpatterns += [url(r'^social/', include('allauth.socialaccount.urls'))]

# Provider urlpatterns, as separate attribute (for reusability).
provider_urlpatterns = []
for provider in providers.registry.get_list():
    try:
        prov_mod = import_module(provider.get_package() + '.urls')
    except ImportError:
        continue
    prov_urlpatterns = getattr(prov_mod, 'urlpatterns', None)
    if prov_urlpatterns:
        provider_urlpatterns += prov_urlpatterns
urlpatterns += provider_urlpatterns

crypto/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('cryptowallet.urls', namespace='crypto')),
    path('accounts/', include('allauth.urls')),
    path('admin/', admin.site.urls)
]

cryptowallet/urls.py
from django.urls import path
from .views import profile, index

from . import views

app_name = 'crypto'

urlpatterns = [
    path('', index.as_view(), name='index'),
    path('profile/', profile.as_view(), name='profile'),
]

templates/cryptobase.html
{% load static %}

<!DOCTYPE html>
<html>

<head>

  {% block title %}

  {% endblock %}

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700&display=swap" rel="stylesheet">

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
    integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">


  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700&display=swap" rel="stylesheet">

  <link rel="stylesheet" href="{% static "css/open-iconic-bootstrap.min.css" %}">
  <link rel="stylesheet" href="{% static "css/animate.css" %}">
  <link rel="stylesheet" href="{% static "css/owl.carousel.min.css" %}">
  <link rel="stylesheet" href="{% static "css/owl.theme.default.min.css" %}">
  <link rel="stylesheet" href="{% static "css/magnific-popup.css" %}">
  <link rel="stylesheet" href="{% static "css/aos.css" %}">
  <link rel="stylesheet" href="{% static "css/ionicons.min.css" %}">
  <link rel="stylesheet" href="{% static "css/bootstrap-datetimepicker.min.css" %}">
  <link rel="stylesheet" href="{% static "css/nouislider.css" %}">
  <link rel="stylesheet" href="{% static "css/flaticon.css" %}">
  <link rel="stylesheet" href="{% static "css/icomoon.css" %}">
  <link rel="stylesheet" href="{% static "css/style.css" %}">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
    integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
    integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
    integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"></script>


  <style>
    section,
    html,
    body {
      height: 100%;
      margin: 0px;
      padding: 0px;
    }

    body {
      background-image: url("{% static "back.jpg" %}");
      background-repeat: no-repeat;
      background-size: cover;
    }

    input[type=text] {
      padding: 6px;
      margin-top: 8px;
      font-size: 17px;
      border: none;
    }

    .search-container {
      float: right;
    }

      {% block style %}

      {% endblock %}
  </style>

  {% block head %}

  {% endblock %}



</head>

<body>
  {% block body %}

  
  
  
  <div>
    <div class="px-0 bg-info navbar-wrap mb-2">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <nav class="navbar px-0 navbar-expand-lg navbar-light">
              <a class="navbar-brand" href="{% url 'crypto:index' %}">Crypto Wallet</a>
              <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample05"
              aria-controls="navbarsExample05" aria-expanded="false" aria-label="Toggle navigation">
              <span class="oi oi-menu"></span>
            </button>
            {% block search %}
            <div class="search-container">
              <form method='post'>
                {% csrf_token %}
                {{form.search}}
                <button type="submit"><i class="fa fa-search"></i></button>
                </form>
              </div>
              {% endblock %}

              <div class="collapse navbar-collapse" id="navbarsExample05">
                <ul class="navbar-nav ml-auto">
                  <li class="nav-item d-flex dropdown">
                    <a class="nav-link d-flex align-items-center dropdown-toggle" href="#" id="navbarDropdown"
                    role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    User
                  </a>
                  <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    {% if not user.is_anonymous %}
                    <a class="dropdown-item" href="{% url 'crypto:index' %}">Home</a>
                    <a class="dropdown-item" href="{% url 'crypto:profile' %}">Edit Profile</a>
                      <a class="dropdown-item" href="{% url 'account_logout' %}">Logout</a>
                      {%else%}
                      <a class="dropdown-item" href="{% url 'account_login' %}">Login</a>
                      <a class="dropdown-item" href="{% url 'account_signup' %}">Resgister</a>
                      {%endif%}
                    </div>
                  </li>
                </ul>
              </div>
            </nav>
          </div>
        </div>
      </div>
    </div>
    
    {% if messages %}
        {% for message in messages %}
        <div class="alert alert-success" role="alert">
            <strong>{{ message|escape }}</strong>
        </div>
        {% endfor %}
    {% endif %}

    <!-- {% if user.is_authenticated %}
      <li><a href="{% url 'account_email' %}">Change E-mail</a></li>
        <li><a href="{% url 'account_logout' %}">Sign Out</a></li>
        {% else %}
        <li><a href="{% url 'account_login' %}">Sign In</a></li>
        <li><a href="{% url 'account_signup' %}">Sign Up</a></li>
        {% endif %} -->

  </div>
  {% block content %}
  {% endblock %}
  {% endblock %}
  {% block extra_body %}
  {% endblock %}
</body>

</html>